import type { Metadata } from "next";
import Link from "next/link";
import { PolicyPage } from "../../src/components/policy-page";

export const metadata: Metadata = {
  title: "Terms of Use | RoomScouter",
  description: "Rules for using RoomScouter's boarding-house discovery and community features.",
};

export default function TermsPage() {
  return (
    <PolicyPage
      title="Terms of Use"
      summary="These terms explain the rules for using RoomScouter, a pilot service for finding and comparing boarding houses near Nueva Vizcaya State University."
    >
      <p className="policy-draft-notice"><strong>Operator details required before public launch.</strong> The legal name and address of the RoomScouter operator and its official contact channel have not been supplied to the project. The operator must insert and approve those details before treating these policies as final.</p>
      <section><h2>1. About the service</h2><p>RoomScouter lets visitors browse approved boarding-house listings. Registered students can save listings, publish one review per listing, and submit private reports. Property owners can submit and maintain listings. Administrators review listings and moderate reports and reviews.</p><p>RoomScouter provides discovery and information tools. It does not arrange or guarantee a rental, reservation, lease, payment, viewing, or communication between users. Students and owners deal directly with each other and make their own checks and agreements.</p></section>
      <section><h2>2. Accounts and access</h2><p>Give accurate account information, keep your sign-in details private, and tell the operator promptly if you believe someone has accessed your account without permission. You are responsible for activity carried out through your account, except where applicable law provides otherwise.</p><p>Choose the student or property-owner role that describes your use. Administrator access is assigned separately. Do not share an account or try to obtain access to another person’s private information or workspace.</p></section>
      <section><h2>3. Rules for listings and community content</h2><p>Owners must have authority to publish a listing and must keep rent, availability, location, amenities, rules, photos, and contact details accurate and lawful. Obtain permission before uploading photos or information about another identifiable person. Do not publish someone else’s private contact details without authority.</p><p>Reviews and reports must be honest, relevant, and based on a genuine interaction or concern. Do not post threats, harassment, discriminatory content, unlawful material, fabricated claims, spam, malware, or personal information that is not needed to describe the issue. Do not use RoomScouter to scrape, probe, disrupt, or bypass its access controls.</p><p>Submitted listings remain subject to administrator review. RoomScouter may reject, hide, or remove material that is inaccurate, unsafe, unlawful, or inconsistent with these terms, and may restrict accounts when necessary to protect users or the service. Moderation does not certify a property or guarantee the truth of every user submission.</p></section>
      <section><h2>4. Public information and user content</h2><p>When an owner submits a listing for publication, the owner authorizes RoomScouter to store, review, display, format, and distribute the listing details, photos, and contact channels as needed to operate the service. Approved listing contact details are shown to visitors so they can contact the owner directly.</p><p>A published review and its rating are visible to the public without the reviewer’s profile being displayed. Reports are private to the reporter and administrators. Favorites are private to the student who saved them. Administrators can access information needed to review listings and handle moderation.</p><p>You retain rights you hold in your content. You give the operator a non-exclusive, worldwide, royalty-free permission to host, reproduce, resize, display, and distribute your submitted content only to provide, secure, and improve RoomScouter and to administer moderation. This permission ends when the content is removed, except for copies retained in backups or records when needed for security, legal obligations, or dispute handling.</p></section>
      <section><h2>5. Property decisions and safety</h2><p>Listing details are supplied by owners and may become outdated. Confirm availability, price, house rules, identity, location, safety, and rental terms directly with the owner before visiting or making a decision. RoomScouter does not inspect, own, manage, endorse, or warrant any property or user, and cannot guarantee that a listing is complete, current, suitable, or safe.</p><p>Use ordinary care when contacting or meeting someone. Do not send money or sensitive documents based only on a listing. Report suspected fraud or unsafe content through the report feature.</p></section>
      <section><h2>6. Availability, suspension, and changes</h2><p>The pilot may be changed, limited, or temporarily unavailable for maintenance or security. We may suspend access where reasonably necessary to address misuse, protect users, or comply with law. We will publish material changes to these terms on this page and update the date above. Continued use after a change takes effect means acceptance only where that is valid under applicable law; where fresh agreement is required, we will request it.</p></section>
      <section><h2>7. Liability and applicable law</h2><p>Nothing in these terms removes rights or remedies that cannot legally be excluded. To the extent permitted by Philippine law, RoomScouter is provided as a discovery service and the operator is not responsible for a rental transaction or for user-provided listing content, except to the extent liability arises from the operator’s own breach of law or other non-excludable obligation.</p><p>These terms are governed by the laws of the Republic of the Philippines, subject to mandatory consumer-protection rules and the jurisdiction of competent courts.</p></section>
      <section><h2>8. Contact and related policies</h2><p>For questions, use the operator’s official support channel: <strong>[operator to provide verified support contact before launch]</strong>. Read the <Link href="/privacy">Privacy Notice</Link> and <Link href="/cookies">Cookie Notice</Link> for details about information and session cookies.</p></section>
    </PolicyPage>
  );
}
