create table public.facilities (
  id smallint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 80)
);

create unique index facilities_name_lower_idx on public.facilities (lower(name));

create table public.utilities (
  id smallint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 80)
);

create unique index utilities_name_lower_idx on public.utilities (lower(name));

create table public.boarding_house_facilities (
  boarding_house_id uuid not null references public.boarding_houses (id) on delete cascade,
  facility_id smallint not null references public.facilities (id) on delete restrict,
  primary key (boarding_house_id, facility_id)
);

create table public.boarding_house_utilities (
  boarding_house_id uuid not null references public.boarding_houses (id) on delete cascade,
  utility_id smallint not null references public.utilities (id) on delete restrict,
  is_included boolean not null,
  details text check (details is null or char_length(trim(details)) between 1 and 240),
  primary key (boarding_house_id, utility_id)
);

create table public.house_rules (
  id uuid primary key default gen_random_uuid(),
  boarding_house_id uuid not null references public.boarding_houses (id) on delete cascade,
  rule_text text not null check (char_length(trim(rule_text)) between 3 and 500),
  position integer not null check (position between 1 and 100),
  unique (boarding_house_id, position)
);

insert into public.facilities (id, name)
values
  (1, 'Wi-Fi'),
  (2, 'Study Area'),
  (3, 'Laundry Area'),
  (4, 'Parking'),
  (5, 'Air Conditioning'),
  (6, 'Private Bathroom'),
  (7, 'Kitchen Access'),
  (8, 'Security/CCTV');

insert into public.utilities (id, name)
values
  (1, 'Electricity'),
  (2, 'Water'),
  (3, 'Internet'),
  (4, 'Cooking Gas');

create function public.queue_listing_attribute_review()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_listing_id uuid;
begin
  if tg_op = 'DELETE' then
    target_listing_id := old.boarding_house_id;
  else
    target_listing_id := new.boarding_house_id;
  end if;

  if (select auth.uid()) is not null and not public.current_user_is_admin() then
    update public.boarding_houses
    set status = 'pending',
        submitted_at = now(),
        moderated_at = null,
        moderated_by = null,
        moderation_note = null
    where id = target_listing_id
      and owner_id = (select auth.uid())
      and status = 'approved';
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function public.queue_listing_attribute_review() from public;

create trigger boarding_house_facilities_queue_review
after insert or update or delete on public.boarding_house_facilities
for each row execute function public.queue_listing_attribute_review();

create trigger boarding_house_utilities_queue_review
after insert or update or delete on public.boarding_house_utilities
for each row execute function public.queue_listing_attribute_review();

create trigger house_rules_queue_review
after insert or update or delete on public.house_rules
for each row execute function public.queue_listing_attribute_review();

alter table public.facilities enable row level security;
alter table public.facilities force row level security;
alter table public.utilities enable row level security;
alter table public.utilities force row level security;
alter table public.boarding_house_facilities enable row level security;
alter table public.boarding_house_facilities force row level security;
alter table public.boarding_house_utilities enable row level security;
alter table public.boarding_house_utilities force row level security;
alter table public.house_rules enable row level security;
alter table public.house_rules force row level security;

revoke all on table public.facilities from public, anon, authenticated;
revoke all on table public.utilities from public, anon, authenticated;
grant select on table public.facilities to anon, authenticated;
grant select on table public.utilities to anon, authenticated;

revoke all on table public.boarding_house_facilities from public, anon, authenticated;
grant select on table public.boarding_house_facilities to anon, authenticated;
grant insert, delete on table public.boarding_house_facilities to authenticated;

revoke all on table public.boarding_house_utilities from public, anon, authenticated;
grant select on table public.boarding_house_utilities to anon, authenticated;
grant insert, delete on table public.boarding_house_utilities to authenticated;
grant update (is_included, details) on table public.boarding_house_utilities to authenticated;

revoke all on table public.house_rules from public, anon, authenticated;
grant select on table public.house_rules to anon, authenticated;
grant insert, delete on table public.house_rules to authenticated;
grant update (rule_text, position) on table public.house_rules to authenticated;

create policy "facilities_select_catalog"
on public.facilities
for select
to anon, authenticated
using (true);

create policy "utilities_select_catalog"
on public.utilities
for select
to anon, authenticated
using (true);

create policy "boarding_house_facilities_select_visible_listing"
on public.boarding_house_facilities
for select
to anon, authenticated
using (
  exists (
    select 1 from public.boarding_houses
    where boarding_houses.id = boarding_house_facilities.boarding_house_id
  )
);

create policy "boarding_house_facilities_manage_owner_or_admin"
on public.boarding_house_facilities
for all
to authenticated
using (
  public.current_user_is_admin()
  or exists (
    select 1 from public.boarding_houses
    where boarding_houses.id = boarding_house_facilities.boarding_house_id
      and boarding_houses.owner_id = (select auth.uid())
      and public.current_user_is_owner()
  )
)
with check (
  public.current_user_is_admin()
  or exists (
    select 1 from public.boarding_houses
    where boarding_houses.id = boarding_house_facilities.boarding_house_id
      and boarding_houses.owner_id = (select auth.uid())
      and public.current_user_is_owner()
  )
);

create policy "boarding_house_utilities_select_visible_listing"
on public.boarding_house_utilities
for select
to anon, authenticated
using (
  exists (
    select 1 from public.boarding_houses
    where boarding_houses.id = boarding_house_utilities.boarding_house_id
  )
);

create policy "boarding_house_utilities_manage_owner_or_admin"
on public.boarding_house_utilities
for all
to authenticated
using (
  public.current_user_is_admin()
  or exists (
    select 1 from public.boarding_houses
    where boarding_houses.id = boarding_house_utilities.boarding_house_id
      and boarding_houses.owner_id = (select auth.uid())
      and public.current_user_is_owner()
  )
)
with check (
  public.current_user_is_admin()
  or exists (
    select 1 from public.boarding_houses
    where boarding_houses.id = boarding_house_utilities.boarding_house_id
      and boarding_houses.owner_id = (select auth.uid())
      and public.current_user_is_owner()
  )
);

create policy "house_rules_select_visible_listing"
on public.house_rules
for select
to anon, authenticated
using (
  exists (
    select 1 from public.boarding_houses
    where boarding_houses.id = house_rules.boarding_house_id
  )
);

create policy "house_rules_manage_owner_or_admin"
on public.house_rules
for all
to authenticated
using (
  public.current_user_is_admin()
  or exists (
    select 1 from public.boarding_houses
    where boarding_houses.id = house_rules.boarding_house_id
      and boarding_houses.owner_id = (select auth.uid())
      and public.current_user_is_owner()
  )
)
with check (
  public.current_user_is_admin()
  or exists (
    select 1 from public.boarding_houses
    where boarding_houses.id = house_rules.boarding_house_id
      and boarding_houses.owner_id = (select auth.uid())
      and public.current_user_is_owner()
  )
);
